import { StyleSheet } from "react-native";

export const navigationStyles = StyleSheet.create({
  drawerScroll: {
    backgroundColor: "#F6FAFD",
  },
  drawerContentContainer: {
    flexGrow: 1,
    paddingTop: 16,
    paddingHorizontal: 12,
    paddingBottom: 20,
    gap: 10,
  },
  drawerHero: {
    borderWidth: 1,
    borderColor: "#D8E2ED",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
  },
  drawerHeroTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  drawerHeroStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  drawerHeroStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1,
    borderColor: "#D8E2ED",
    borderRadius: 12,
    paddingVertical: 5,
    paddingHorizontal: 9,
  },
  drawerHeroStatusText: {
    fontSize: 9,
    fontWeight: "700",
  },
  drawerHeroMeta: {
    fontSize: 9,
    fontWeight: "600",
  },
  drawerBrandIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D8E2ED",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  drawerBrandImage: {
    width: 28,
    height: 28,
  },
  drawerBrandTextWrap: {
    flex: 1,
  },
  drawerBrandTitle: {
    fontSize: 13,
    fontWeight: "900",
  },
  drawerBrandSubtitle: {
    fontSize: 9,
    fontWeight: "600",
    marginTop: 1,
  },
  groupBlock: {
    borderWidth: 0,
    borderRadius: 16,
    backgroundColor: "#FDFEFF",
    overflow: "hidden",
    shadowColor: "#0E1828",
    shadowOpacity: 0.035,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
  },
  groupHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingTop: 9,
    paddingBottom: 7,
    borderBottomWidth: 1,
  },
  groupTitle: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  groupBody: {
    paddingHorizontal: 7,
    paddingVertical: 7,
    gap: 3,
  },
  groupItem: {
    minHeight: 40,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: "row",
    alignItems: "center",
  },
  groupItemIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  groupItemText: {
    flex: 1,
    fontSize: 11,
    fontWeight: "600",
    marginLeft: 8,
  },
  groupItemTextActive: {
    fontWeight: "800",
  },
  groupItemChevron: {
    marginLeft: 8,
  },
  signOutBtn: {
    height: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D8E2ED",
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  signOutText: {
    fontSize: 11,
    fontWeight: "800",
  },
  drawerFooterSpacer: {
    flex: 1,
    minHeight: 4,
  },
  disabledBtn: {
    opacity: 0.6,
  },
  topBarWrap: {
    paddingHorizontal: 12,
    paddingBottom: 6,
  },
  topBarShell: {
    borderWidth: 1,
    borderColor: "#D8E2ED",
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 8,
    shadowColor: "#0E1828",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  topBarInner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    minHeight: 40,
  },
  topBarTitleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  topTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  topRouteIcon: {
    width: 22,
    height: 22,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  topTitleText: {
    flex: 1,
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 0.1,
  },
  topTitleTextCompact: {
    fontSize: 13,
  },
  topSubtitleText: {
    fontSize: 10,
    fontWeight: "600",
  },
  topActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  topIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#D8E2ED",
    alignItems: "center",
    justifyContent: "center",
  },
  topMenuBtn: {
    width: 44,
    height: 44,
    borderRadius: 13,
  },
  topIconBtnCompact: {
    width: 36,
    height: 36,
  },
  topCartBtn: {
    width: 36,
    height: 36,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#D8E2ED",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  topCartBtnCompact: {
    width: 38,
    height: 36,
  },
  topCartBadge: {
    position: "absolute",
    right: -4,
    top: -5,
    minWidth: 16,
    height: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D8E2ED",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  topCartBadgeText: {
    color: "#FFFFFF",
    fontSize: 8,
    fontWeight: "800",
    lineHeight: 11,
  },
  topDivider: {
    height: 1,
    marginTop: 8,
    marginBottom: 8,
  },
  topMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 8,
  },
  topMetaLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  topMetaBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1,
    borderColor: "#D8E2ED",
    borderRadius: 12,
    paddingVertical: 4,
    paddingHorizontal: 8,
    minHeight: 22,
  },
  topMetaText: {
    fontSize: 9,
    fontWeight: "700",
  },
  topDateChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1,
    borderColor: "#D8E2ED",
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    minHeight: 22,
  },
  topDateText: {
    fontSize: 9,
    fontWeight: "700",
  },
});
